name: Build and deploy Docker app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'genai-teams-qa'   # Your App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: 'DOCKER|Dockerfile'
